config/routes.rb
require "api_constraints"

Rails.application.routes.draw do
  devise_for :agents, path: "auth",
                      controllers: {
                        registrations: "registrations",
                        confirmations: "confirmations"
                      }

  mount RailsAdmin::Engine => "/manage", :as => "rails_admin"
  devise_for :admins, path: "admin"

  resources :after_signup, only: [:edit, :update]
  resources :contact_forms, only: [:new, :create]
  resources :support_forms, only: [:new, :create]

  resources :visitors
  resources :activities, only: [:index]
  resources :departments
  resources :chats, only: [:index, :show]
  resources :invoice_payments, only: [:index, :show]
  resources :websites, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :agents, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :rapid_responses, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :settings, only: [:update]

  resources :offline_forms, only: [:index, :edit, :update]
  resources :prechat_forms, only: [:index, :edit, :update]
  resources :chat_widgets, only: [:index, :edit, :update]
  resources :invitations, only: [:index, :edit, :update]
  resources :organizations, only: [:edit, :update]

  mount StripeEvent::Engine => "/stripe-events"
  resources :subscriptions, only: [:new, :create, :edit, :update, :destroy]
  resources :coupons, only: [:show]

  root to: "home#dashboard", via: :get

  delete "signout", to: "home#signout", as: "signout"
  get "monitor", to: "home#monitor", as: "monitor"
  get "dashboard", to: "home#dashboard", as: "dashboard"
  get "code", to: "home#code", as: "code"

  post "send_code", to: "send_code#show", as: "send_code"
  post "add_ftp_server", to: "after_signup#add_ftp_server", as: "add_ftp_server"

  get "documentation/start", to: "documentation#start", as: "doc_start"
  get "documentation/general", to: "documentation#general", as: "doc_general"
  get "documentation/websites", to: "documentation#websites", as: "doc_websites"
  get "documentation/monitor", to: "documentation#monitor", as: "doc_monitor"

  get "terms-of-service", to: "static_pages#terms", as: "terms"
  get "privacy-policy", to: "static_pages#privacy", as: "privacy"

  namespace :api, defaults: {format: "json"} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :agents, only: [:update, :show]
      resources :chat_monitor, only: [:index, :update]
      resources :widgets, only: [:index]
    end
  end

  # Sidekiq monitoring
  require "sidekiq/web"
  # authenticate :admin do
  mount Sidekiq::Web => "sidekiq"
  # end

  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_agent!, raise: false
  before_action :validate_admin, except: [:monitor, :signout]

  def monitor
  end

  def signout
    current_agent.availability = Agent.availabilities[:offline]
    current_agent.save
    sign_out_and_redirect(current_agent)
  end

  def dashboard
    @websites = Website.where(organization_id: current_agent.organization_id)
    @agents = Agent.where(organization_id: current_agent.organization_id)

    @blog_feed = [] #Feedjira::Feed.fetch_and_parse("http://blog.providechat.com/feed")
  end

  def code
    @websites = Website.where(organization_id: current_agent.organization_id)
  end

  def contact
  end

  private

  def validate_admin
    if current_agent.access_level == "agent"
      redirect_to monitor_path
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_agents_availability.html.slim
table.table.table-bordered
  thead
    tr
      th Name
      th Current Availability
  tbody
    - agents.each do |agent|
      tr
        td= link_to agent.name, edit_agent_path(agent)
        td
          label class=(agent.availability == 'online' ? 'label label-success' : 'label label-danger')
            = agent.availability.titleize

app/views/home/_settings.html.haml
.modal.fade{role: "dialog", tabindex: "-1", id: "modal-settings"}
  .modal-dialog
    .modal-content
      = form_for(agent, url: setting_path(agent), html: {id: "agent-settings", class: 'form-horizontal', multipart: true}, remote: true) do |f|
      
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
          %h4.modal-title Settings
        .modal-body
          .alert.alert-danger{id: "settings-error", style: "display: none;"}
            %p Error updating settings, please contact support.
          .alert.alert-success{id: "settings-success", style: "display: none;"}
            %p Settings were updated successfully.
          
          %h4
            %i.fa.fa-volume-up
            &nbsp;Alert me with a sound when:
          %fieldset
            .form-group
              .col-sm-8.col-sm-offset-1.col-xs-12.col-xs-offset-0
                .input-group
                  .checkbox
                    = f.label :active_chat_sound do
                      = f.check_box :active_chat_sound
                      A new message arrives in the selected chat
                .input-group
                  .checkbox
                    = f.label :background_chat_sound do
                      = f.check_box :background_chat_sound
                      A new message arrives in a background chat
                .input-group
                  .checkbox
                    = f.label :visitor_arrived_sound do
                      = f.check_box :visitor_arrived_sound
                      A new visitor arrives on the website

        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
          = f.submit "Save changes", class: "btn btn-primary"

- content_for :scripts do
  :javascript
    $("#agent-settings").on("ajax:success", function(e, data, status, xhr) {
      $("#settings-error").hide();
      return $("#settings-success").fadeIn().delay(2000).fadeOut();
    }).on("ajax:error", function(e, data, status, xhr) {
      $("#settings-success").hide();
      return $("#settings-error").fadeIn().delay(2000).fadeOut();
    });

app/views/home/_settings.html.slim
.modal.fade#modal-settings role="dialog" tabindex="-1"
  .modal-dialog
    .modal-content
      = form_for(agent, url: setting_path(agent), html: {id: "agent-settings", class: 'form-horizontal', multipart: true}, remote: true) do |f|
        .modal-header
          button.close aria-label="Close" data-dismiss="modal" type="button"
            span aria-hidden="true" ×
          h4.modal-title Settings
        .modal-body
          .alert.alert-danger#settings-error style="display: none;"
            p Error updating settings, please contact support.
          .alert.alert-success#settings-success style="display: none;"
            p Settings were updated successfully.
          
          h4
            i.fa.fa-volume-up
            | &nbsp;Alert me with a sound when:
          fieldset
            .form-group
              .col-sm-8.col-sm-offset-1.col-xs-12.col-xs-offset-0
                .input-group
                  .checkbox
                    = f.label :active_chat_sound do
                      = f.check_box :active_chat_sound
                      | A new message arrives in the selected chat
                .input-group
                  .checkbox
                    = f.label :background_chat_sound do
                      = f.check_box :background_chat_sound
                      | A new message arrives in a background chat
                .input-group
                  .checkbox
                    = f.label :visitor_arrived_sound do
                      = f.check_box :visitor_arrived_sound
                      | A new visitor arrives on the website

        .modal-footer
          button.btn.btn-default data-dismiss="modal" type="button" Close
          = f.submit "Save changes", class: "btn btn-primary"

- content_for :scripts do

  javascript:
    $("#agent-settings").on("ajax:success", function(e, data, status, xhr) {
      $("#settings-error").hide();
      return $("#settings-success").fadeIn().delay(2000).fadeOut();
    }).on("ajax:error", function(e, data, status, xhr) {
      $("#settings-success").hide();
      return $("#settings-error").fadeIn().delay(2000).fadeOut();
    });

app/views/home/_websites_listing.html.slim
- if @websites.count == 0
  table.table.table-bordered
    tr
      td colspan="3"
        | You haven't added any websites yet. #{link_to "Add Website", new_website_path, { title: "Add Website", class: "btn btn-primary btn-sm" }}
- else
  table.table.table-bordered style="table-layout:fixed;"
    thead
      tr
        th style="width: 40%;" Name
        th style="width: 40%;" URL
        th style="width: 20%;" Widget
    tbody
      - @websites.each do |website|
        tr
          td style="width: 40%; overflow: hidden;"
            = link_to website.name, edit_website_path(website)
          td style="width: 40%; overflow: hidden;"
            = website.url
          td style="width: 20%;"
            = widget_status_label(website.widget_status)

app/views/home/_widget_include_code.html.erb
<script id="pc-widget">
  var ProvideChat = window.ProvideChat || {};
  (function() {
    ProvideChat.org_id = <%= organization_id %>;
    var pc = document.createElement('script'); pc.type = 'text/javascript'; pc.async = true;
    pc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'widget.providechat.com/widget.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(pc, s);
  })();
</script>

app/views/home/code.html.haml
= render 'layouts/page_header', :title => 'Chat Widget', :icon => 'fa-toggle-up', :subpage => 'Website Code'

.col-sm-12.col-md-8.col-lg-8
  #website-code.jarviswidget.jarviswidget-color-darken{data: {widget_editbutton: "false",
     widget_fullscreenbutton: "false", widget_colorbutton: "false",
     widget_deletebutton: "false", widget_togglebutton: "false"}}

    %header
      %span.widget-icon
        %i.fa.fa-code
      %h2 Website Code
    %div
      .widget-body.no-padding
        - if @websites.count > 0
          .alert.alert-info.no-margin.fade.in
            %div{style: "float: left;"}
              %i.fa-fw.fa.fa-info
            %div{style: "margin-left: 24px;"}
              To install the Provide Chat Widget, paste this code (unaltered, in it’s entirety) on every page of your website just before the closing &lt;/body&gt; tag.

          .code-container
            .row
              .col-md-12
                %textarea#widget-code.codetext= render partial: "home/widget_include_code", locals: { organization_id: current_agent.organization_id }

                .pull-right
                  %a.btn.btn-default.btn-sm#copy-code{data: {clipboard_action: "copy", clipboard_target: "#widget-code"}}
                    Copy to clipboard
                    %i.fa.fa-files-o
            %hr
            .row
              .col-md-12
                %a{href: "#", id: "email-code", "data-target": ".send-code-modal", "data-toggle": "modal"}
                  Send these instructions to your webmaster
                .alert.alert-success#success_msg{style: "display: none;"} Email sent successfully
        - else
          .alert.alert-warning.no-margin.fade.in
            %h4.alert-heading No websites configured yet!
            %br
            You have not yet added any websites, please #{link_to "add a website", new_website_path}.

= render partial: "shared/send_email_to_webmaster"

- content_for :scripts do
  :javascript
    $(document).ready(function () {
      var clipboard = new Clipboard('#copy-code');
    });

app/views/home/dashboard.erb
<%= render 'layouts/page_header', :title => 'Dashboard' %>

<div class="row">
  <div class="col-sm-6 col-md-6 col-lg-6">

    <div class="jarviswidget jarviswidget-color-blueLight" id="website-widget" data-widget-editbutton="false" data-widget-colorbutton="false" data-widget-togglebutton="false" data-widget-deletebutton="false" data-widget-fullscreenbutton="false" data-widget-sortable="false" role="widget"> 

		<header role="heading">
			<span class="widget-icon"> <i class="fa fa-cloud"></i> </span>
			<h2><strong>Your Websites</strong></h2>		
					
			<div class="widget-toolbar" role="menu">
        <%= link_to "Website Setup", websites_path, { title: "Website Setup", class: "btn btn-default" }  %>
			</div>
		<span class="jarviswidget-loader"><i class="fa fa-refresh fa-spin"></i></span></header>

		<!-- widget div-->
		<div role="content">
							
			<!-- widget content -->
			<div class="widget-body">
				
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Name</th>
              <th>URL</td>
              <th>Widget Installed?</td>
            </tr>
          </thead>
          <% @websites.each do |website| %>
            <tr>
             <td><%= website.name %></td>
             <td><%= website.url %></td>
             <td>
                Checking &nbsp;<%= image_tag "select2-spinner.gif" %> 
             </td>
            </tr>
          <% end %>
          <% if @websites.count == 0 %>
            <tr>
              <td colspan="2">You haven't added any websites yet. <%= link_to "Add Website", new_website_path, { title: "Add Website", class: "btn btn-primary" }  %></td>
          <% end %>
        </table>
				
			</div>
			<!-- end widget content -->
			
		</div>
		<!-- end widget div -->
		
	</div>

    <h4>Latest Blog Entries</h4>
  </div>
  <div class="col-sm-6 col-md-6 col-lg-6">
    
    <div class="jarviswidget jarviswidget-color-blueLight" id="website-widget" data-widget-editbutton="false" data-widget-colorbutton="false" data-widget-togglebutton="false" data-widget-deletebutton="false" data-widget-fullscreenbutton="false" data-widget-sortable="false" role="widget"> 

		<header role="heading">
			<span class="widget-icon"> <i class="fa fa-user"></i> </span>
			<h2><strong>Your Agents</strong></h2>		
					
			<div class="widget-toolbar" role="menu">
        <%= link_to "Manage Agents", agents_path, { title: "Manage Agents", class: "btn btn-default" }  %>
			</div>
		<span class="jarviswidget-loader"><i class="fa fa-refresh fa-spin"></i></span></header>

		<!-- widget div-->
		<div role="content">
							
			<!-- widget content -->
			<div class="widget-body">
				
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Name</th>
              <th>Current Availability</td>
            </tr>
          </thead>
          <% @agents.each do |agent| %>
            <tr>
             <td><a href="#" onclick="#', 'content');"><%= agent.name %></a></td>
             <td>
               <% if agent.availability == 'online'%>
                 <span style='color: #228b22;'><strong>Online</strong></span>
               <% else %>
                 <span style='color: #b22222;'><strong>Offline</strong></span>
              <% end %>
              </td>
            </tr>
          <% end %>
          <tr>
            <td style="background-color: #E5E5E5; border-bottom: 1px solid #BBBBBB;" class="fieldtext">
              <a href="#" onclick="loadHTML('operators.php', 'content');"><b>More Details</b></a>
            </td>
            <td style="background-color: #E5E5E5; border-bottom: 1px solid #BBBBBB;" class="fieldtext" align="right">
               You are currently using 1 of 12 available operators
            </td>
          </tr>
        </table>
				
			</div>
			<!-- end widget content -->
			
		</div>
		<!-- end widget div -->
		
	</div>

    <h4>Upgrade Your Account</h4>
    <table border="0" cellpadding="8" cellspacing="0" width="100%" style="border-left: 1px solid #DDDDDD; border-right: 1px solid #DDDDDD;">
      <tr>
        <td class="maintext" style="border-bottom: 1px solid #BBBBBB; background-color: #E5E5E5;" width="40%">
         <b>If you would like to upgrade your account, simply click on one of the links below to upgrade to your
        desired account.</b>
      </td>
     </tr>
      <tr>
        <td class="fieldtext" style="border-bottom: 1px solid #BBBBBB; background-color: #E5E5E5;" width="40%">
          <i>Please Note: Upgrades have a 3-day trial period, no payment is made until after the 3-day trial</i>
       </td>
     </tr>
     <tr>
       <td class="fieldtext" style="border-bottom: 1px solid #BBBBBB;" align="center">
         <br />
       </td>
     </tr>
    </table>
  </div>
</div>

app/views/home/dashboard.html.haml
= render 'layouts/page_header', :title => 'Dashboard'

.col-xs-12.col-sm-6.col-md-6
  #website-widget.jarviswidget.jarviswidget-color-darken{:role => "widget"}
    %header{:role => "heading"}
      %span.widget-icon
        %i.fa.fa-cloud
      %h2
        %strong Your Websites
      .widget-toolbar{:role => "menu"}
        = link_to "Manage Websites", websites_path, { title: "Website Setup", class: "btn btn-primary" }
      %span.jarviswidget-loader
        %i.fa.fa-refresh.fa-spin
    %div{:role => "content"}
      .widget-body.no-padding
        = render :partial => 'websites_listing', :locals => { websites: @websites}

.col-xs-12.col-sm-6.col-md-6
  #agents-widget.jarviswidget.jarviswidget-color-darken{:role => "widget"}
    %header{:role => "heading"}
      %span.widget-icon
        %i.fa.fa-user
      %h2
        %strong Your Agents
      .widget-toolbar{:role => "menu"}
        = link_to "Manage Agents", agents_path, { title: "Manage Agents", class: "btn btn-primary" }
      %span.jarviswidget-loader
        %i.fa.fa-refresh.fa-spin
    %div{:role => "content"}
      .widget-body.no-padding
        = render :partial => 'agents_availability', :locals => { agents: @agents}
        .widget-footer
          .pull-right
            - if current_agent.organization.account_type == 'trial' || current_agent.organization.account_type == 'free'
              You are currently using your maximum available agents.
            - elsif current_agent.organization.account_type == 'paid' && current_agent.organization.subscription
              You are currently using #{current_agent.organization.agents.count} of 
              #{current_agent.organization.subscription.quantity} available agents.
            - elsif current_agent.organization.account_type == 'master'
              You have unlimited agents
            - else
              You are currently using your maximum available agents.

.clearfix

.col-xs-12.col-sm-6.col-md-6
  #blog-widget.jarviswidget.jarviswidget-color-darken{:role => "widget"}
    %header{:role => "heading"}
      %span.widget-icon
        %i.fa.fa-rss
      %h2
        %strong Latest Blog Entries
      %span.jarviswidget-loader
        %i.fa.fa-refresh.fa-spin
    %div{:role => "content"}
      .widget-body.no-padding
        %table.table.table-bordered
          - @blog_feed.entries.first(5).each do |entry|
            %tr
              %td
                = link_to entry.title, entry.url, :target => "blank"
                -
                %i
                  = entry.published.strftime("%B %e, %Y")
          - if @blog_feed.entries.count == 0
            %tr
              %td No blog entries found

- if current_agent.access_level == 'superadmin'

  .col-xs-12.col-sm-6.col-md-6
    #account-widget.jarviswidget.jarviswidget-color-darken{:role => "widget"}
      %header{:role => "heading"}
        %span.widget-icon
          %i.fa.fa-gears
        %h2
          %strong Your Account
        %span.jarviswidget-loader
          %i.fa.fa-refresh.fa-spin
      %div{:role => "content"}
        .widget-body
          .row
            - if current_agent.organization.account_type == 'trial'
              .col-xs-2
                = image_tag 'icons/subscribe.png', class: "dashboard-icon"
              .col-xs-10
                .alert.alert-info
                  %h4 You currently have #{current_agent.organization.remaining_trial_days} days left in your trial period.
                  %br
                  %p
                    Click the button below to start your paid subscription, otherwise your 
                    account will downgrade to the free version once the trial period expires.
   
            - elsif current_agent.organization.account_type == 'paid' && current_agent.organization.subscription
              .col-xs-2
                = image_tag 'icons/subscribed.png', class: "dashboard-icon"
              .col-xs-10
                .alert.alert-info
                  %h4 You have an active subscription of #{current_agent.organization.subscription.quantity} agents.
                  %br
                  %p
                    - if current_agent.organization.subscription.interval == 'month'
                      You are on our monthly payment plan.
                    - elsif current_agent.organization.subscription.interval == 'year'
                      You are on our yearly payment plan.
                    Your next payment is scheduled for #{current_agent.organization.subscription.next_payment}.

            - elsif current_agent.organization.account_type == 'free'
              .col-xs-2
                = image_tag 'icons/subscribe.png', class: "dashboard-icon"
              .col-xs-10
                %h4 You have a free account, which is limited to a single concurrent chat. 
                %br
                %p
                  To unlock multiple chats or to add multiple agents, start your 
                  subscription today.

            - elsif current_agent.organization.account_type == 'master'
              .col-xs-2
                = image_tag 'icons/subscribed.png', class: "dashboard-icon"
              .col-xs-10
                .alert.alert-info
                  %h4 You have a master account with unlimited agents.
                  %br

          .widget-footer
            .pull-right
              - if current_agent.organization.account_type == 'trial' || current_agent.organization.account_type == 'free'
                = link_to "Start your subscription", new_subscription_path, class: "btn btn-success btn-large"
              - elsif current_agent.organization.account_type == 'paid'
                = link_to "Modify Your Subscription", edit_subscription_path(current_agent.organization.subscription), class: "btn btn-success btn-large"
            .clearfix

app/views/home/dashboard.html.slim
= render 'layouts/page_header', :title => 'Dashboard'

.col-xs-12.col-sm-6.col-md-6
  #website-widget.jarviswidget.jarviswidget-color-darken role="widget"
    header role="heading"
      span.widget-icon
        i.fa.fa-cloud
      h2
        strong Your Websites
      .widget-toolbar role="menu"
        = link_to "Manage Websites", websites_path, { title: "Website Setup", class: "btn btn-primary" }
      span.jarviswidget-loader
        i.fa.fa-refresh.fa-spin
    div role="content"
      .widget-body.no-padding
        = render :partial => 'websites_listing', :locals => { websites: @websites}

.col-xs-12.col-sm-6.col-md-6
  #agents-widget.jarviswidget.jarviswidget-color-darken role="widget"
    header role="heading"
      span.widget-icon
        i.fa.fa-user
      h2
        strong Your Agents
      .widget-toolbar role="menu"
        = link_to "Manage Agents", agents_path, { title: "Manage Agents", class: "btn btn-primary" }
      span.jarviswidget-loader
        i.fa.fa-refresh.fa-spin
    div role="content"
      .widget-body.no-padding
        = render :partial => 'agents_availability', :locals => { agents: @agents}
        .widget-footer
          .pull-right
            - if current_agent.organization.account_type == 'trial' || current_agent.organization.account_type == 'free'
              | You are currently using your maximum available agents.
            - elsif current_agent.organization.account_type == 'paid' && current_agent.organization.subscription
              | You are currently using #{current_agent.organization.agents.count} of 
              #{current_agent.organization.subscription.quantity} available agents.
            - elsif current_agent.organization.account_type == 'master'
              | You have unlimited agents
            - else
              | You are currently using your maximum available agents.

.clearfix

.col-xs-12.col-sm-6.col-md-6
  #blog-widget.jarviswidget.jarviswidget-color-darken role="widget"
    header role="heading"
      span.widget-icon
        i.fa.fa-rss
      h2
        strong Latest Blog Entries
      span.jarviswidget-loader
        i.fa.fa-refresh.fa-spin
    div role="content"
      .widget-body.no-padding
        table.table.table-bordered
          - @blog_feed.entries.first(5).each do |entry|
            tr
              td
                = link_to entry.title, entry.url, :target => "blank"
                | &nbsp;-&nbsp; 
                i= entry.published.strftime("%B %e, %Y")
          - if @blog_feed.entries&.count == 0
            tr
              td No blog entries found

- if current_agent.access_level == 'superadmin'

  .col-xs-12.col-sm-6.col-md-6
    #account-widget.jarviswidget.jarviswidget-color-darken role="widget"
      header role="heading"
        span.widget-icon
          i.fa.fa-gears
        h2
          strong Your Account
        span.jarviswidget-loader
          i.fa.fa-refresh.fa-spin
      div role="content"
        .widget-body
          .row
            - if current_agent.organization.account_type == 'trial'
              .col-xs-2
                = image_tag 'icons/subscribe.png', class: "dashboard-icon"
              .col-xs-10
                .alert.alert-info
                  h4 You currently have #{current_agent.organization.remaining_trial_days} days left in your trial period.
                  br
                  p
                    | Click the button below to start your paid subscription, otherwise your 
                    | account will downgrade to the free version once the trial period expires.
   
            - elsif current_agent.organization.account_type == 'paid' && current_agent.organization.subscription
              .col-xs-2
                = image_tag 'icons/subscribed.png', class: "dashboard-icon"
              .col-xs-10
                .alert.alert-info
                  h4 You have an active subscription of #{current_agent.organization.subscription.quantity} agents.
                  br
                  p
                    - if current_agent.organization.subscription.interval == 'month'
                      | You are on our monthly payment plan.
                    - elsif current_agent.organization.subscription.interval == 'year'
                      | You are on our yearly payment plan.
                    | Your next payment is scheduled for #{current_agent.organization.subscription.next_payment}.

            - elsif current_agent.organization.account_type == 'free'
              .col-xs-2
                = image_tag 'icons/subscribe.png', class: "dashboard-icon"
              .col-xs-10
                h4 You have a free account, which is limited to a single concurrent chat. 
                br
                p
                  | To unlock multiple chats or to add multiple agents, start your 
                  | subscription today.

            - elsif current_agent.organization.account_type == 'master'
              .col-xs-2
                = image_tag 'icons/subscribed.png', class: "dashboard-icon"
              .col-xs-10
                .alert.alert-info
                  h4 You have a master account with unlimited agents.
                  br

          .widget-footer
            .pull-right
              - if current_agent.organization.account_type == 'trial' || current_agent.organization.account_type == 'free'
                = link_to "Start your subscription", new_subscription_path, class: "btn btn-success btn-large"
              - elsif current_agent.organization.account_type == 'paid'
                = link_to "Modify Your Subscription", edit_subscription_path(current_agent.organization.subscription), class: "btn btn-success btn-large"
            .clearfix