config/routes.rb
require "api_constraints"

Rails.application.routes.draw do
  devise_for :agents, path: "auth",
                      controllers: {
                        registrations: "registrations",
                        confirmations: "confirmations"
                      }

  mount RailsAdmin::Engine => "/manage", :as => "rails_admin"
  devise_for :admins, path: "admin"

  resources :after_signup, only: [:edit, :update]
  resources :contact_forms, only: [:new, :create]
  resources :support_forms, only: [:new, :create]

  resources :visitors
  resources :activities, only: [:index]
  resources :departments
  resources :chats, only: [:index, :show]
  resources :invoice_payments, only: [:index, :show]
  resources :websites, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :agents, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :rapid_responses, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :settings, only: [:update]

  resources :offline_forms, only: [:index, :edit, :update]
  resources :prechat_forms, only: [:index, :edit, :update]
  resources :chat_widgets, only: [:index, :edit, :update]
  resources :invitations, only: [:index, :edit, :update]
  resources :organizations, only: [:edit, :update]

  mount StripeEvent::Engine => "/stripe-events"
  resources :subscriptions, only: [:new, :create, :edit, :update, :destroy]
  resources :coupons, only: [:show]

  root to: "home#dashboard", via: :get

  delete "signout", to: "home#signout", as: "signout"
  get "monitor", to: "home#monitor", as: "monitor"
  get "dashboard", to: "home#dashboard", as: "dashboard"
  get "code", to: "home#code", as: "code"

  post "send_code", to: "send_code#show", as: "send_code"
  post "add_ftp_server", to: "after_signup#add_ftp_server", as: "add_ftp_server"

  get "documentation/start", to: "documentation#start", as: "doc_start"
  get "documentation/general", to: "documentation#general", as: "doc_general"
  get "documentation/websites", to: "documentation#websites", as: "doc_websites"
  get "documentation/monitor", to: "documentation#monitor", as: "doc_monitor"

  get "terms-of-service", to: "static_pages#terms", as: "terms"
  get "privacy-policy", to: "static_pages#privacy", as: "privacy"

  namespace :api, defaults: {format: "json"} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :agents, only: [:update, :show]
      resources :chat_monitor, only: [:index, :update]
      resources :widgets, only: [:index]
    end
  end

  # Sidekiq monitoring
  require "sidekiq/web"
  # authenticate :admin do
  mount Sidekiq::Web => "sidekiq"
  # end

  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"
end

app/controllers/prechat_forms_controller.rb
class PrechatFormsController < ApplicationController
  before_action :authenticate_agent!, raise: false
  before_action :validate_admin

  def index
    website_id = params.key?(:website_id) ? params[:website_id] : Website.where(organization_id: current_agent.organization_id).first.id

    return unless website_id
    @prechat_form = PrechatForm.find_by(website_id: website_id)
    redirect_to edit_prechat_form_path(@prechat_form)
  end

  def edit
    @prechat_form = PrechatForm.find(params[:id])
    @chat_widget = ChatWidget.find_by(website_id: @prechat_form.website_id)
    @websites = Website.where(organization_id: current_agent.organization_id)
    @departments = Website.find(@prechat_form.website_id).departments
  end

  def update
    @prechat_form = PrechatForm.find(params[:id])

    if @prechat_form.process_update(params, prechat_form_params)
      redirect_to edit_prechat_form_path(@prechat_form),
        flash: {success: "Prechat survey was successfully updated."}
    else
      render :edit
    end
  end

  private

  def prechat_form_params
    params.require(:prechat_form).permit(:intro_text, :name_text, :email_text,
      :email_enabled, :department_text,
      :department_enabled, :message_text,
      :button_text)
  end

  def validate_admin
    if current_agent.access_level == "agent"
      redirect_to monitor_path
    end
  end
end

app/views/prechat_forms/_form.html.haml
= form_for(@prechat_form, :html => {class: 'form-horizontal'}) do |f|
  = render "layouts/error_messages", :f => @prechat_form
  %header
  %fieldset
    .form-group
      %label.col-md-4.control-label= f.label :intro_text, "Introduction"
      .col-md-8
        = f.text_area :intro_text, :class => "form-control", :rows => 4

    .form-group
      %label.col-md-4.control-label= f.label :name_text, "Name Field"
      .col-md-8
        = f.text_field :name_text, :class => "form-control"

    .form-group
      %label.col-md-4.control-label= f.label :email_text, "Email Field"
      .col-md-8
        = f.text_field :email_text, :class => "form-control"
        .help-text{:style => "font-size: 10px;"}
          %label.checkbox-label
            = f.check_box :email_enabled, :class => "aligned-checkbox"
            Display Email Field
            
    .form-group
      %label.col-md-4.control-label= f.label :department_text, "Department Field"
      .col-md-8
        = f.text_field :department_text, :class => "form-control"
        .help-text{:style => "font-size: 10px;"}
          %label.checkbox-label
            = f.check_box :department_enabled, :class => "aligned-checkbox"
            Display Department Field

    .form-group
      %label.col-md-4.control-label= f.label :message_text, "Initial Question Field"
      .col-md-8
        = f.text_field :message_text, :class => "form-control"

    .form-group
      %label.col-md-4.control-label= f.label :button_text, "Start Chat Button"
      .col-md-8
        = f.text_field :button_text, :class => "form-control"

  %hr

  %footer
    = f.submit "Apply Changes", :class => "btn btn-primary", :name => "save_changes"
    = f.submit "Cancel", :class => "btn btn-default", :name => "cancel_changes", data: { confirm: 'Are you sure you want to cancel your current changes?' }
    = f.submit "Reset Defaults", :class => "btn btn-danger", :name => "restore_defaults", data: { confirm: 'Are you sure you want to reset the prechat form to default settings?' }
  %hr

app/views/prechat_forms/_pre_chat.html.haml
.widget-preview-container
  #pc-chat-window{:style => "display: block;"}
    .chat-widget.chat-widget-open
      .chat-widget-header{:style => "background-color: \##{@chat_widget.color};"}
        %span{id: "pc-title-message"}
          = @chat_widget.title_message
        %div{:id => "chat-header-images"}
          = image_tag "widget/down-arrow.png", id: "close-chat-widget"
          = image_tag "widget/close.png", id: "end-chat"

      #chat-widget-content
        .chat-widget-container
          %div{:style => "margin: 10px; font-family: arial, verdana, helvetica; font-size: 13px;"}
            %p= @prechat_form.intro_text
            %p
              %input#start-chat-text-box-1{:placeholder => @prechat_form.name_text, :type => "text"}/

            - if @prechat_form.email_enabled
              %p
                %input#start-chat-text-box-2{:placeholder => @prechat_form.email_text, :type => "text"}/

            - if @prechat_form.department_enabled && @departments.count > 0
              %p
                %select#unavailable-department
                  %option{:value => "0"} Any Department
                  - @departments.each do |department|
                    %option{:value => department.id}= department.name
            %textarea#start-chat-question{:placeholder => @prechat_form.message_text, :rows => "4"}
            %input#start-chat-btn{:style => "color: #333333; font-family: arial, verdana, helvetica; font-size: 12px; height: 40px;", :type => "submit", :value => "  #{@prechat_form.button_text}  "}

      #chat-widget-footer
        %p{id: "powered-by"}
          %a{:href => "#"}
            Live Chat Software powered by Provide Chat

app/views/prechat_forms/edit.html.haml
.col-md-12
  %h1.page-title.txt-color-blueDark{style: "float: left;"}
    Chat Widget
    &nbsp;/&nbsp;
    Pre-chat Survey for
  = form_tag(prechat_forms_path, method: 'get', class: 'form-inline', 
      id: 'edit_prechat_form', style: 'display: inline; padding-left: 8px;') do
    .form-group
      = select_tag "website_id", 
        options_from_collection_for_select(@websites, "id", "url", @prechat_form.website_id), 
        id: "website_id", class: "form-control website-select"

= render partial: 'layouts/flash_messages', flash: flash

- if @prechat_form
  .col-sm-12
    #prechat-survey.jarviswidget.jarviswidget-color-darken{data: {widget_editbutton: "false",
     widget_fullscreenbutton: "false", widget_colorbutton: "false",
     widget_deletebutton: "false", widget_togglebutton: "false"}}
      %header
        %span.widget-icon
          %i.fa.fa-toggle-up
        %h2 Pre-chat Survey
      %div
        .widget-body.no-padding
          .alert.alert-info.no-margin.fade.in
            %div{:style => "float: left;"}
              %i.fa-fw.fa.fa-info
            %div{:style => "margin-left: 24px;"}
              This is the form your visitor completes before they initiate a chat with you.
          .form-container
            .col-sm-12.col-sm-5.col-lg-6
              = render 'form'
            .col-sm-12.col-md-7.col-lg-6
              = render 'pre_chat'

-content_for :scripts do
  :javascript
    function initialize_website_dropdown() {
      $('#website_id').on ('change', function() {
        $('#edit_prechat_form').submit();
      });
    }

    $( document ).ready(function() {
      initialize_website_dropdown();
    });

app/views/prechat_forms/index.html.haml
.col-md-12
  %h1.page-title.txt-color-blueDark
    Chat Widget
    %i.fa.fa-angle-double-right
    Pre-chat Survey

= render partial: 'layouts/flash_messages', flash: flash

.col-sm-12.col-md-8.col-lg-8
  .alert.alert-warning.alert-block
    %h4.alert-heading No websites configured yet!
    %br
    You have not yet added any websites, please #{link_to "add a website", new_website_path}
    and then you'll be able to customize the pre-chat survey.