config/routes.rb
require "api_constraints"

Rails.application.routes.draw do
  devise_for :agents, path: "auth",
                      controllers: {
                        registrations: "registrations",
                        confirmations: "confirmations"
                      }

  mount RailsAdmin::Engine => "/manage", :as => "rails_admin"
  devise_for :admins, path: "admin"

  resources :after_signup, only: [:edit, :update]
  resources :contact_forms, only: [:new, :create]
  resources :support_forms, only: [:new, :create]

  resources :visitors
  resources :activities, only: [:index]
  resources :departments
  resources :chats, only: [:index, :show]
  resources :invoice_payments, only: [:index, :show]
  resources :websites, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :agents, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :rapid_responses, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :settings, only: [:update]

  resources :offline_forms, only: [:index, :edit, :update]
  resources :prechat_forms, only: [:index, :edit, :update]
  resources :chat_widgets, only: [:index, :edit, :update]
  resources :invitations, only: [:index, :edit, :update]
  resources :organizations, only: [:edit, :update]

  mount StripeEvent::Engine => "/stripe-events"
  resources :subscriptions, only: [:new, :create, :edit, :update, :destroy]
  resources :coupons, only: [:show]

  root to: "home#dashboard", via: :get

  delete "signout", to: "home#signout", as: "signout"
  get "monitor", to: "home#monitor", as: "monitor"
  get "dashboard", to: "home#dashboard", as: "dashboard"
  get "code", to: "home#code", as: "code"

  post "send_code", to: "send_code#show", as: "send_code"
  post "add_ftp_server", to: "after_signup#add_ftp_server", as: "add_ftp_server"

  get "documentation/start", to: "documentation#start", as: "doc_start"
  get "documentation/general", to: "documentation#general", as: "doc_general"
  get "documentation/websites", to: "documentation#websites", as: "doc_websites"
  get "documentation/monitor", to: "documentation#monitor", as: "doc_monitor"

  get "terms-of-service", to: "static_pages#terms", as: "terms"
  get "privacy-policy", to: "static_pages#privacy", as: "privacy"

  namespace :api, defaults: {format: "json"} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :agents, only: [:update, :show]
      resources :chat_monitor, only: [:index, :update]
      resources :widgets, only: [:index]
    end
  end

  # Sidekiq monitoring
  require "sidekiq/web"
  # authenticate :admin do
  mount Sidekiq::Web => "sidekiq"
  # end

  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"
end

app/controllers/rapid_responses_controller.rb
class RapidResponsesController < ApplicationController
  before_action :set_rapid_response, only: [:edit, :update, :destroy]

  def index
    @rapid_responses = RapidResponse.all
  end

  def new
    @rapid_response = RapidResponse.new
  end

  def edit
  end

  def create
    @rapid_response = RapidResponse.new(rapid_response_params)

    respond_to do |format|
      if @rapid_response.save
        format.html { redirect_to @rapid_response, notice: "Rapid response was successfully created." }
        format.json { render :show, status: :created, location: @rapid_response }
      else
        format.html { render :new }
        format.json { render json: @rapid_response.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @rapid_response.update(rapid_response_params)
        format.html { redirect_to @rapid_response, notice: "Rapid response was successfully updated." }
        format.json { render :show, status: :ok, location: @rapid_response }
      else
        format.html { render :edit }
        format.json { render json: @rapid_response.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @rapid_response.destroy
    respond_to do |format|
      format.html { redirect_to rapid_responses_url, notice: "Rapid response was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_rapid_response
    @rapid_response = RapidResponse.find(params[:id])
  end

  def rapid_response_params
    params.require(:rapid_response).permit(:organization_id, :name, :text,
      :order, :ancestry, :status)
  end
end

app/views/rapid_responses/_form.html.haml
= form_for(@rapid_response) do |f|
  - if @rapid_response.errors.any?
    #error_explanation
      %h2
        = pluralize(@rapid_response.errors.count, "error")
        prohibited this rapid_response from being saved:
      %ul
        - @rapid_response.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :organization_id
    %br/
    = f.number_field :organization_id
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :text
    %br/
    = f.text_field :text
  .field
    = f.label :order
    %br/
    = f.number_field :order
  .field
    = f.label :ancestry
    %br/
    = f.text_field :ancestry
  .field
    = f.label :status
    %br/
    = f.text_field :status
  .actions
    = f.submit

app/views/rapid_responses/edit.html.haml
%h1 Editing rapid_response
= render 'form'
= link_to 'Show', @rapid_response
|
\#{link_to 'Back', rapid_responses_path}

app/views/rapid_responses/index.html.haml
= render 'layouts/page_header', :title => 'Settings', :icon => 'fa-sitemap', :subpage => 'Rapid Responses'

.col-sm-12.col-md-12.col-lg-12
  #wid-id-0.jarviswidget.jarviswidget-color-darken
    %header
      %span.widget-icon
        %i.fa.fa-flash
      %h2 Rapid Responses
      .widget-toolbar{:role => "menu"}
        = link_to 'New Website', new_website_path, { title: "Add Website", class: "btn btn-primary" }
      %span.jarviswidget-loader
        %i.fa.fa-refresh.fa-spin
    %div{:role => "content"}

      #nestable-menu
        %button.btn.btn-default{"data-action" => "expand-all", :type => "button"}
          Expand All
        %button.btn.btn-default{"data-action" => "collapse-all", :type => "button"}
          Collapse All
      #nestable.dd
        %ol.dd-list
          - @rapid_responses.roots.each do |rapid_response|
            %li.dd-item.dd3-item{"data-id" => rapid_response.id}
              .dd-handle.dd3-handle
                Drag
              .dd3-content
                = rapid_response.name
              %ol.dd-list
                - rapid_response.children.each do |rapid_response_child|
                  %li.dd-item.dd3-item{"data-id" => "16"}
                    .dd-handle.dd3-handle
                      Drag
                    .dd3-content
                      = rapid_response_child.name
                      .pull-right
                        = rapid_response_child.text
      %br/
      = link_to 'New Rapid response', new_rapid_response_path

app/views/rapid_responses/new.html.haml
%h1 New rapid_response
= render 'form'
= link_to 'Back', rapid_responses_path